# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r
cache: packages
sudo: required
r_build_args: "--compact-vignettes"
r_packages:
  - devtools
r_github_packages:
  - r-lib/covr
os:
  - linux
r:
  - release
  - devel
env:
  - COMPILER=gxx-7
matrix:
  fast_finish: true
  include:
    - os: osx
      r: release
      env: COMPILER=clang
  allow_failures:
    - r: devel
# see https://thecoatlessprofessor.com/programming/selecting-an-alternative-compiler-for-r-package-testing-on-travis-ci/
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - gfortran-7
      #- r-cran-rspectra
before_install:
  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then
      sudo tlmgr install placeins cleveref framed;
    else
      sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 60 --slave /usr/bin/g++ g++ /usr/bin/g++-7;
      sudo update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-7 50;
    fi
  - |
    Rscript() {
      # https://github.com/travis-ci/travis-ci/issues/4190#issuecomment-353342526
      while sleep 60; do echo "=====[ still running ]====="; done &
      command Rscript "$@" > /dev/null 2>&1
      kill %1
    }
    Rscript -e 'print("A");print(1);'
after_success:
  - if [[ ("$TRAVIS_R_VERSION" != "devel") && ("$TRAVIS_OS_NAME" == "linux") ]]; then
      Rscript codecov.R;
    fi
notifications:
  email:
    on_success: change
    on_failure: change
